# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fd0479dbccd181f4797b9a8f6a1e677c8f7b2b3a2042a0790247904a412bdbc57553006233cc9b4cca93468db47adf03bf944f57926cd40a3634937f8c9e8c4

test:
  secret_key_base: 12788a6190a9c2d0f0018f6113331014a5b75042eeb786ab0cbb96c33f1bfbaa4d9e9553fe45fc71a8fa6f2522adf8d4f2a7f656446fab43c6d91fad60c3e346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
